#!/usr/bin/env python3
"""
Generate the OPPU per-user training configs for the ten new User-LoRA tracks.

Five tasks × two Task-LoRA bases each, run in parallel:

  task           R-track (base = One-LoRA FT)   PT-track (base = Per-Task-LoRA)
  LaMP_2_news    R10                            PT3
  LaMP_1         R11                            PT4
  LaMP_7         R12                            PT5
  LaMP_2_movies  R13                            PT6
  LaMP_5         R14                            PT7

None of these five tasks was in A1-lamp's 3-task mix, so unlike LaMP-3/4
there is no "original A1-lamp round to re-run later" — running both bases
from the start is the natural choice, not a re-run. (A1-lamp is skipped even
for LaMP-7, where it would technically be viable, to keep every new round on
the same two bases rather than reopening A1-lamp as a special case.)

Recipe: the OPPU hyperparameters, unchanged and not relitigated — r=8,
q_proj+v_proj only, alpha=16, dropout=0.05, LR=1e-5, weight_decay=1e-2,
3 epochs, cosine + 3% warmup, per_device_batch=2, grad_accum=4. The ONLY
per-task value is `max_seq_length`, which is read from that task's T3 sizing
JSON (`<task>_t3_sizing.json`) rather than copied from another round — R5's
1024 was measured on LaMP-3's corpora and means nothing for, say, LaMP-5's
abstracts.

This writes BOTH artifacts:
  - the per-track template  train/config/user_lora_<tag>_oppu_<track>_template.json
    (committed; the human-readable record of the recipe + base adapter)
  - the per-user configs    train/config/user_lora_<tag>_oppu_<user>_<track>.json
    (gitignored; deterministically derivable from template + pool JSON)

Mirrors data/lamp_user_stats/{round5,round6,ptl,pt2}_gen_configs.py, collapsed
into one parameterized script because there are ten tracks this time rather
than one.

Usage (CPU-only, <1s per track; needs the task's T3 sizing JSON on disk):
    python data/lamp_user_stats/newtask_gen_configs.py --task LaMP_7 --track pt5
    python data/lamp_user_stats/newtask_gen_configs.py --all --overwrite
"""

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
USER_STATS_DIR = PROJECT_ROOT / "data" / "lamp_user_stats"
CONFIG_DIR = PROJECT_ROOT / "train" / "config"

ONE_LORA_FT = "train/checkpoints/a2_lamp_1ep_seed0/final"

# task -> (short tag, pool JSON, corpus suffix, per-task Task-LoRA checkpoint)
TASKS = {
    "LaMP_2_news": ("lamp2news", "LaMP_2_news_top27_users.json",
                    "records_bm25k4", "train/checkpoints/per_task_lamp2_news_1ep_seed0/final"),
    "LaMP_1": ("lamp1", "LaMP_1_top100_users.json",
               "unsup", "train/checkpoints/per_task_lamp1_1ep_seed0/final"),
    "LaMP_7": ("lamp7", "LaMP_7_top100_users.json",
               "unsup", "train/checkpoints/per_task_lamp7_1ep_seed0/final"),
    "LaMP_2_movies": ("lamp2movies", "LaMP_2_movies_top100_users.json",
                      "bm25k4", "train/checkpoints/per_task_lamp2_movies_1ep_seed0/final"),
    "LaMP_5": ("lamp5", "LaMP_5_top100_users.json",
               "bm25k4", "train/checkpoints/per_task_lamp5_1ep_seed0/final"),
}

# track -> (task, uses One-LoRA FT?)
TRACKS = {
    "r10": ("LaMP_2_news", True),   "pt3": ("LaMP_2_news", False),
    "r11": ("LaMP_1", True),        "pt4": ("LaMP_1", False),
    "r12": ("LaMP_7", True),        "pt5": ("LaMP_7", False),
    "r13": ("LaMP_2_movies", True), "pt6": ("LaMP_2_movies", False),
    "r14": ("LaMP_5", True),        "pt7": ("LaMP_5", False),
}


def template_doc(task, track, base_adapter, max_seq_length, suffix) -> str:
    base_name = "One-LoRA FT" if base_adapter == ONE_LORA_FT else f"Per-Task-LoRA({task})"
    trainer = ("train/train_unsupervised_clm.py (OPPU right-shifted-history "
               "objective — raw text, loss on every token)"
               if suffix == "unsup" else "train/train.py (supervised SFT)")
    return (
        f"{track.upper()} — per-user User-LoRA for {task}, stacked on "
        f"{base_name} ({base_adapter}). Trained by {trainer}. Recipe is the "
        f"OPPU one used by every User-LoRA round since R5 (r=8 q+v, alpha=16, "
        f"dropout=0.05, LR=1e-5, weight_decay=1e-2, 3 epochs, cosine + 3% "
        f"warmup, per_device_batch=2, grad_accum=4), unchanged and not "
        f"relitigated. max_seq_length={max_seq_length} comes from this task's "
        f"own T3 sizing pass ({task}_t3_sizing.json), NOT copied from another "
        f"round. Per-user instantiations live at "
        f"train/config/user_lora_{TASKS[task][0]}_oppu_<user>_{track}.json, "
        f"generated by data/lamp_user_stats/newtask_gen_configs.py (gitignored)."
    )


def build_template(task, track, base_adapter, max_seq_length, suffix) -> dict:
    return {
        "_doc": template_doc(task, track, base_adapter, max_seq_length, suffix),
        "condition": "<<CONDITION>>",
        "seed": 0,
        "model_name_or_path": "data/models/SmolLM3-3B",
        "base_adapter": base_adapter,
        "dataset_path": "<<DATASET_PATH>>",
        "output_dir": "<<OUTPUT_DIR>>",
        "lora": {
            "r": 8,
            "lora_alpha": 16,
            "lora_dropout": 0.05,
            "target_modules": ["q_proj", "v_proj"],
            "bias": "none",
            "task_type": "CAUSAL_LM",
        },
        "data": {"max_seq_length": max_seq_length},
        "trainer": {
            "num_train_epochs": 3,
            "per_device_train_batch_size": 2,
            "gradient_accumulation_steps": 4,
            "learning_rate": 1e-5,
            "weight_decay": 0.01,
            "adam_beta1": 0.9,
            "adam_beta2": 0.999,
            "adam_epsilon": 1e-8,
            "max_grad_norm": 1.0,
            "lr_scheduler_type": "cosine",
            "warmup_ratio": 0.03,
            "bf16": True,
            "gradient_checkpointing": True,
            "gradient_checkpointing_kwargs": {"use_reentrant": False},
            "save_strategy": "epoch",
            "save_total_limit": 1,
            "logging_steps": 1,
            "optim": "adamw_torch",
            "report_to": "none",
            "remove_unused_columns": False,
            "dataloader_num_workers": 2,
        },
        "wandb": {
            "_doc": "Disabled — report_to above is 'none'.",
            "project": "mobileFT_distill",
            "run_name": "<<CONDITION>>",
        },
    }


def gen_track(track: str, overwrite: bool) -> int:
    task, use_one_lora = TRACKS[track]
    tag, pool_file, suffix, per_task_ckpt = TASKS[task]
    base_adapter = ONE_LORA_FT if use_one_lora else per_task_ckpt

    # --- max_seq_length from this task's own T3 sizing --------------------
    t3_path = USER_STATS_DIR / f"{task}_t3_sizing.json"
    if not t3_path.exists():
        sys.exit(
            f"ERROR: missing {t3_path}. Run "
            f"`newtask_t3_sizing.py --task {task}` first — max_seq_length must "
            f"be measured on this task's corpora, never copied from another round."
        )
    t3 = json.loads(t3_path.read_text())
    max_seq_length = t3.get("max_seq_length_pinned")
    if not max_seq_length:
        sys.exit(
            f"ERROR: {t3_path} has max_seq_length_pinned=null — that sizing run "
            f"hit the 8192 positional ceiling and stopped. Resolve that before "
            f"generating {track} configs."
        )

    # --- base adapter must actually exist ---------------------------------
    if not (PROJECT_ROOT / base_adapter / "adapter_config.json").exists():
        sys.exit(f"ERROR: base adapter {base_adapter} has no adapter_config.json.")

    # --- template ----------------------------------------------------------
    template_path = CONFIG_DIR / f"user_lora_{tag}_oppu_{track}_template.json"
    if template_path.exists() and not overwrite:
        sys.exit(f"ERROR: refusing to overwrite {template_path}. Pass --overwrite.")
    template = build_template(task, track, base_adapter, max_seq_length, suffix)
    template_path.write_text(json.dumps(template, indent=2) + "\n")
    print(f"[gen] template -> {template_path} (max_seq_length={max_seq_length})",
          flush=True)

    # --- per-user configs --------------------------------------------------
    pool_path = USER_STATS_DIR / pool_file
    if not pool_path.exists():
        sys.exit(f"ERROR: missing pool {pool_path}; run select_top_users_newtasks.py.")
    fps = [u["user_fingerprint"] for u in json.loads(pool_path.read_text())["users"]]

    out_paths = {fp: CONFIG_DIR / f"user_lora_{tag}_oppu_{fp}_{track}.json"
                 for fp in fps}
    existing = [p for p in out_paths.values() if p.exists()]
    if existing and not overwrite:
        sys.exit(f"ERROR: refusing to overwrite {len(existing)} existing configs "
                 f"(first: {existing[0]}). Pass --overwrite.")

    written = 0
    missing_corpora = []
    for fp in fps:
        cfg = json.loads(json.dumps(template))  # deep copy
        cfg["condition"] = f"user_lora_{tag}_{fp}_{track}_oppu"
        cfg["dataset_path"] = f"data/lamp_user_train_{task}_{fp}_{suffix}.jsonl"
        cfg["output_dir"] = f"train/checkpoints/user_lora_{tag}_{fp}_{track}_seed0"
        cfg["wandb"]["run_name"] = cfg["condition"]

        # Spot-asserts, same style as pt2_gen_configs.py.
        assert cfg["lora"]["r"] == 8, cfg["lora"]
        assert cfg["lora"]["target_modules"] == ["q_proj", "v_proj"], cfg["lora"]
        assert cfg["trainer"]["learning_rate"] == 1e-5, cfg["trainer"]
        assert cfg["trainer"]["weight_decay"] == 0.01, cfg["trainer"]
        assert cfg["trainer"]["num_train_epochs"] == 3, cfg["trainer"]
        assert cfg["base_adapter"] == base_adapter, cfg["base_adapter"]

        if not (PROJECT_ROOT / cfg["dataset_path"]).exists():
            missing_corpora.append(fp)
        out_paths[fp].write_text(json.dumps(cfg, indent=2) + "\n")
        written += 1

    if missing_corpora:
        print(f"[warn] {len(missing_corpora)}/{len(fps)} users have no corpus on "
              f"disk yet (e.g. {missing_corpora[:3]}) — configs written anyway, "
              f"but the training batch will fail until the corpora are built.",
              flush=True)
    print(f"[gen] {written} per-user configs -> "
          f"{CONFIG_DIR}/user_lora_{tag}_oppu_<user>_{track}.json", flush=True)
    return written


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--track", choices=sorted(TRACKS))
    parser.add_argument("--task", choices=sorted(TASKS),
                        help="generate both of this task's tracks")
    parser.add_argument("--all", action="store_true",
                        help="generate all ten tracks")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    if args.all:
        tracks = sorted(TRACKS)
    elif args.task:
        tracks = sorted(t for t, (task, _) in TRACKS.items() if task == args.task)
    elif args.track:
        tracks = [args.track]
    else:
        sys.exit("ERROR: pass one of --track / --task / --all.")

    total = sum(gen_track(t, args.overwrite) for t in tracks)
    print(f"[gen] done: {total} configs across {len(tracks)} track(s)", flush=True)


if __name__ == "__main__":
    main()
