universe              = docker
docker_image          = ghcr.io/gordofreemo/smollm3-train:ver3
executable            = condor/download_model.py
output                = /home/ange00008/projects/mobileFT_distill/runlogs/download_model.$(ClusterId).$(ProcId).out
error                 = /home/ange00008/projects/mobileFT_distill/runlogs/download_model.$(ClusterId).$(ProcId).err
log                   = /home/ange00008/projects/mobileFT_distill/runlogs/download_model.$(ClusterId).log
should_transfer_files = YES
environment           = MODEL_OUT_DIR=/home/ange00008/projects/mobileFT_distill/data/models/SmolLM3-3B
request_CPUs          = 2
request_memory        = 16G
request_disk          = 12G
requirements          = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted   = true
+WantScratchMounted   = true
queue 1
