#!/usr/bin/env python3
"""Emit the Condor sub files for the OPPU faithful-replication round.

EDIT THIS SCRIPT, NOT THE .sub FILES (same convention as gen_newtask_subs.py,
gen_warm_subs.py, gen_r9_subs.py).

Generated:
    condor/oppu_rep_smoke.sub        7 jobs  (both stages, 1 test user, per task)
    condor/oppu_rep_task_lora.sub    7 jobs  (full task-LoRA training + RAG-arm eval)
    condor/oppu_rep_user.sub       ~65 jobs  (per-user OPPU stage, sharded 10 users/job)

Guards baked into every sub (project standard as of 2026-08-10):
  - tyr1/tyr2/modi excluded (CUDA-busy oversubscription ×2, uncorrectable ECC)
  - require_gpus Capability [8.0, 10.0) — Blackwell sm_120 has no ver4 kernels
  - PROJECT_ROOT + Condor ids in environment

The user stage needs the task-LoRA checkpoints on disk first: submit
oppu_rep_task_lora.sub, verify, then submit oppu_rep_user.sub.
`condor_submit` stays user-run for the batch subs.
"""

from pathlib import Path

ROOT = "/home/ange00008/projects/mobileFT_distill"
IMAGE = "ghcr.io/gordofreemo/smollm3-train:ver4"

# their task order; (task, n_test_users) — 2N has only 49 users in the release
TASKS = [
    ("citation", 100),
    ("movie_tagging", 100),
    ("news_categorize", 49),
    ("news_headline", 100),
    ("product_rating", 101),
    ("scholarly_title", 101),
    ("tweet_paraphrase", 100),
]
USERS_PER_SHARD = 10

GPU_REQS = ('requirements          = UidDomain == "cs.uni-saarland.de" && '
            'Machine != "tyr1.hpc.uni-saarland.de" && '
            'Machine != "tyr2.hpc.uni-saarland.de" && '
            'Machine != "modi.hpc.uni-saarland.de"')
def header(tag, executable, arguments, memory="32G", gpu=True):
    gpu_block = f"""request_GPUs          = 1
request_CPUs          = 4
request_memory        = {memory}
{GPU_REQS}
+WantGPUHomeMounted   = true
gpus_minimum_memory     = 40000
gpus_minimum_capability = 8.0
require_gpus            = Capability >= 8.0 && Capability < 10.0
max_job_retirement_time = 28800
""" if gpu else f"""request_CPUs          = 4
request_memory        = {memory}
requirements          = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted   = true
"""
    return f"""universe              = docker
docker_image          = {IMAGE}
executable            = {executable}
arguments             = {arguments}

output                = {ROOT}/runlogs/{tag}.$(ClusterId).$(ProcId).out
error                 = {ROOT}/runlogs/{tag}.$(ClusterId).$(ProcId).err
log                   = {ROOT}/runlogs/{tag}.$(ClusterId).log

should_transfer_files = YES
stream_output           = true
stream_error            = true
when_to_transfer_output = ON_EXIT_OR_EVICT
environment           = "PROJECT_ROOT={ROOT} CONDOR_CLUSTER_ID=$(ClusterId) CONDOR_PROC_ID=$(ProcId)"

{gpu_block}"""


def smoke_sub():
    s = ("# OPPU-replication smoke: both stages, 1 test user, all 7 tasks.\n"
         "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
         + header("oppu_rep_smoke_$(task)", f"{ROOT}/oppu_replication/smoke.sh", "$(task)",
                  memory="48G")  # product_rating's 2.8 GB user_others.json is json.load'd in-job
         + "\nqueue task from (\n"
         + "".join(f"    {t}\n" for t, _ in TASKS)
         + ")\n")
    return s


def task_lora_sub():
    s = ("# OPPU-replication stage 1: task-LoRA training (their recipe, k=1) +\n"
         "# RAG-arm eval over all test users. One job per task.\n"
         "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
         + header("oppu_rep_task_$(task)",
                  f"{ROOT}/oppu_replication/run_task_lora.py",
                  "--task_name $(task) --k 1",
                  memory="48G")  # product_rating's 2.8 GB user_others.json is json.load'd in-job
         + "\nqueue task from (\n"
         + "".join(f"    {t}\n" for t, _ in TASKS)
         + ")\n")
    return s


def user_sub():
    rows = []
    for t, n in TASKS:
        for start in range(0, n, USERS_PER_SHARD):
            end = min(start + USERS_PER_SHARD, n)
            rows.append(f"    {t} {start} {end}\n")
    s = ("# OPPU-replication stage 2: per-user LoRA + OPPU+RAG-arm eval, sharded\n"
         f"# {USERS_PER_SHARD} users/job. Needs stage-1 checkpoints on disk.\n"
         "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
         + header("oppu_rep_user_$(task)_$(ustart)",
                  f"{ROOT}/oppu_replication/run_oppu.py",
                  ("--task_name $(task) --k 1 "
                   f"--task_lora {ROOT}/train/checkpoints/oppu_rep/$(task)/task_lora_k1 "
                   "--user-start $(ustart) --user-end $(uend)"))
         + "\nqueue task, ustart, uend from (\n"
         + "".join(rows)
         + ")\n")
    return s


def base_sub():
    s = ("# OPPU-replication base arm: bare SmolLM3 + their k=1 retrieval prompts,\n"
         "# eval-only (no training). One job per task. Chart/writeup baseline.\n"
         "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
         + header("oppu_rep_base_$(task)",
                  f"{ROOT}/oppu_replication/run_task_lora.py",
                  "--task_name $(task) --k 1 --base-only")
         + "\nqueue task from (\n"
         + "".join(f"    {t}\n" for t, _ in TASKS)
         + ")\n")
    return s


FIX_ARGS = ("--prompt-file {r}/oppu_replication/prompt_fixed.json "
            "--out-root {r}/results/oppu_rep_fixed "
            "--ckpt-root {r}/train/checkpoints/oppu_rep_fixed").format(r=ROOT)


def lamp1fix_smoke_sub():
    return ("# LaMP-1 repaired-prompt smoke (OUR repair — PATCHES.md P18):\n"
            "# both stages, 1 test user, prompt_fixed.json, separate roots.\n"
            "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
            + header("oppu_rep_lamp1fix_smoke",
                     f"{ROOT}/oppu_replication/smoke_lamp1fix.sh", "")
            + "\nqueue 1\n")


def lamp1fix_stage1_sub():
    common = f"--task_name citation --k 1 {FIX_ARGS}"
    return ("# LaMP-1 repaired-prompt stage 1: base arm (eval-only) + task-LoRA\n"
            "# training/eval, both under prompt_fixed.json + separate roots.\n"
            "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
            + header("oppu_rep_lamp1fix_stage1_$(ProcId)",
                     f"{ROOT}/oppu_replication/run_task_lora.py",
                     f"{common} --base-only",
                     memory="48G")
            + "\nqueue 1\n"
            + f"\narguments             = {common}\nqueue 1\n")


def lamp1fix_user_sub():
    n = dict(TASKS)["citation"]
    rows = [f"    {s} {min(s + USERS_PER_SHARD, n)}\n"
            for s in range(0, n, USERS_PER_SHARD)]
    return ("# LaMP-1 repaired-prompt stage 2: per-user OPPU shards on the fixed\n"
            "# task-LoRA. Needs stage-1 checkpoint on disk first.\n"
            "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
            + header("oppu_rep_lamp1fix_user_$(ustart)",
                     f"{ROOT}/oppu_replication/run_oppu.py",
                     (f"--task_name citation --k 1 {FIX_ARGS} "
                      f"--task_lora {ROOT}/train/checkpoints/oppu_rep_fixed/citation/task_lora_k1 "
                      "--user-start $(ustart) --user-end $(uend)"))
            + "\nqueue ustart, uend from (\n" + "".join(rows) + ")\n")


def base_score_sub():
    return ("# Score the base arms (their evaluator + rouge over all preds).\n"
            "# CPU-only; NEVER run this on a login node (2 GB cgroup cap).\n"
            "# The ver4 image lacks evaluate/scipy -> bootstrap wrapper installs\n"
            "# them in-container. Generated by condor/gen_oppu_subs.py.\n\n"
            + header("oppu_rep_base_score",
                     f"{ROOT}/oppu_replication/run_scoring_in_container.sh",
                     f"{ROOT}/eval/plot_oppu_rep.py --score-only",
                     memory="16G", gpu=False)
            + "\nqueue 1\n")


def ablate_smoke_sub():
    return ("# Recipe-ablation + seed-re-decode smoke: movie tagging, 1 user,\n"
            "# all three new code paths (P19 r5 recipe, P20 eval-only x2).\n"
            "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
            + header("oppu_rep_ablate_smoke",
                     f"{ROOT}/oppu_replication/smoke_ablate.sh", "")
            + "\nqueue 1\n")


def ablate_user_sub():
    n = dict(TASKS)["movie_tagging"]
    rows = [f"    {s} {min(s + USERS_PER_SHARD, n)}\n"
            for s in range(0, n, USERS_PER_SHARD)]
    return ("# Recipe ablation cold arm: movie-tagging user stage at the R5 recipe\n"
            "# bundle (P19), same task-LoRA/data/prompts/decoding as the hot arm.\n"
            "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
            + header("oppu_rep_ablate_user_$(ustart)",
                     f"{ROOT}/oppu_replication/run_oppu.py",
                     (f"--task_name movie_tagging --k 1 --user-recipe r5 --tag _r5 "
                      f"--task_lora {ROOT}/train/checkpoints/oppu_rep/movie_tagging/task_lora_k1 "
                      "--user-start $(ustart) --user-end $(uend)"))
            + "\nqueue ustart, uend from (\n" + "".join(rows) + ")\n")


def redecode_sub():
    n = dict(TASKS)["movie_tagging"]
    shard_w = 20
    rows = []
    for seed in (1, 2):
        for s in range(0, n, shard_w):
            rows.append(f"    {seed} {s} {min(s + shard_w, n)}\n")
    task_arm = ("# Seed-robustness re-decode of the movie-tagging headline: both arms\n"
                "# regenerated at seeds 1 and 2 from the saved adapters (P20 eval-only).\n"
                "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
                + header("oppu_rep_redecode_task_s$(seed)",
                         f"{ROOT}/oppu_replication/run_task_lora.py",
                         "--task_name movie_tagging --k 1 --eval-only "
                         "--seed $(seed) --tag _seed$(seed)")
                + "\nqueue seed from (\n    1\n    2\n)\n")
    oppu_arm = ("\n# oppu arm, 5 shards x 2 seeds\n"
                + header("oppu_rep_redecode_oppu_s$(seed)_$(ustart)",
                         f"{ROOT}/oppu_replication/run_oppu.py",
                         (f"--task_name movie_tagging --k 1 --eval-only "
                          f"--task_lora {ROOT}/train/checkpoints/oppu_rep/movie_tagging/task_lora_k1 "
                          "--seed $(seed) --tag _seed$(seed) "
                          "--user-start $(ustart) --user-end $(uend)"))
                + "\nqueue seed, ustart, uend from (\n" + "".join(rows) + ")\n")
    return task_arm, oppu_arm


def ablate_score_sub():
    rows = ["    _r5 . _r5\n", "    _seed1 _seed1 _seed1\n", "    _seed2 _seed2 _seed2\n"]
    return ("# Score the ablation + re-decode arms of movie tagging. The '.' task\n"
            "# tag means untagged (cold arm shares the original task baseline).\n"
            "# CPU-only, in-container bootstrap. Generated by gen_oppu_subs.py.\n\n"
            + header("oppu_rep_ablate_score_$(otag)",
                     f"{ROOT}/oppu_replication/run_scoring_in_container.sh",
                     (f"{ROOT}/eval/oppu_rep_score.py --task movie_tagging "
                      "--oppu-tag $(otag) --task-tag $(ttag) --out-tag $(gtag)"),
                     memory="16G", gpu=False)
            + "\nqueue otag, ttag, gtag from (\n" + "".join(rows) + ")\n")


def power_subsample_sub():
    return ("# Eval-design power analysis: subsample s queries/user from the OPPU\n"
            "# pairs files, measure detection rate of the already-measured effects.\n"
            "# CPU-only, scipy via the in-container bootstrap. Generated by\n"
            "# condor/gen_oppu_subs.py — edit the generator.\n\n"
            + header("oppu_rep_power_subsample",
                     f"{ROOT}/oppu_replication/run_scoring_in_container.sh",
                     f"{ROOT}/eval/oppu_power_subsample.py",
                     memory="8G", gpu=False)
            + "\nqueue 1\n")


def lamp1fix_score_sub():
    return ("# Score the repaired-LaMP-1 arms (task vs oppu, their evaluator +\n"
            "# paired stats). CPU-only, in-container bootstrap for evaluate/scipy.\n"
            "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
            + header("oppu_rep_lamp1fix_score",
                     f"{ROOT}/oppu_replication/run_scoring_in_container.sh",
                     (f"{ROOT}/eval/oppu_rep_score.py --task citation "
                      f"--results-root {ROOT}/results/oppu_rep_fixed"),
                     memory="16G", gpu=False)
            + "\nqueue 1\n")


def main():
    out = {
        "condor/oppu_rep_base.sub": base_sub(),
        "condor/oppu_rep_smoke.sub": smoke_sub(),
        "condor/oppu_rep_task_lora.sub": task_lora_sub(),
        "condor/oppu_rep_user.sub": user_sub(),
        "condor/oppu_rep_base_score.sub": base_score_sub(),
        "condor/oppu_rep_lamp1fix_smoke.sub": lamp1fix_smoke_sub(),
        "condor/oppu_rep_lamp1fix_stage1.sub": lamp1fix_stage1_sub(),
        "condor/oppu_rep_lamp1fix_user.sub": lamp1fix_user_sub(),
        "condor/oppu_rep_lamp1fix_score.sub": lamp1fix_score_sub(),
        "condor/oppu_rep_ablate_smoke.sub": ablate_smoke_sub(),
        "condor/oppu_rep_ablate_user.sub": ablate_user_sub(),
        "condor/oppu_rep_redecode_task.sub": redecode_sub()[0],
        "condor/oppu_rep_redecode_oppu.sub": redecode_sub()[1],
        "condor/oppu_rep_ablate_score.sub": ablate_score_sub(),
        "condor/oppu_rep_power_subsample.sub": power_subsample_sub(),
    }
    for path, content in out.items():
        p = Path(ROOT) / path
        p.write_text(content)
        print(f"wrote {path}")
    n_user_jobs = sum(-(-n // USERS_PER_SHARD) for _, n in TASKS)
    print(f"smoke: {len(TASKS)} jobs | task_lora: {len(TASKS)} jobs | user: {n_user_jobs} jobs")


if __name__ == "__main__":
    main()
