#!/usr/bin/env python3
"""
Emit the LongLaMP decoding sweep sub (Branch A, step 1).

WHY
---
The 2026-08-04 degeneration audit (results/longlamp_degeneration_audit_*.json,
confirmed in-container cluster 179247) showed every LongLaMP Task-LoRA arm runs
away under plain greedy decoding:

    task      Task-LoRA >600w   median words   gold median
    abstract       30/100            142            144.5
    review         83/100            817            211.5
    topic          83/100            802            208.0
    base model      0/100            167            144.5   <-- no adapter

So the regression headlines for LL1 (0.343 -> 0.182) and LL3 (0.281 -> 0.131)
are measured on output that is 4x gold length in the median. Whether those
regressions are real or artifacts is the open question this sweep exists to
answer, and it is answered WITHOUT retraining -- every adapter is on disk.

PROTOCOL -- the part that is easy to get wrong
----------------------------------------------
Select the decoding config on the DEV split, never on test, and then apply the
winner identically to every arm. LL1 was right to refuse to sweep decoding
against the test metric; its mistake was abandoning the sweep rather than
moving it to dev.

The top-100 pool JSONs carry only `test_record_ids` -- there are no dev ids --
so a dev sweep runs UNFILTERED with `--limit`, NOT `--user-records-from-file`.
Reaching for the latter out of habit silently gives the wrong thing.

STOPPING RULE, pre-registered and mechanical
--------------------------------------------
A config is admissible when its degeneration rate at >600 words is near zero.
Among admissible configs, pick the best dev ROUGE-1. Both numbers come out of
the sweep: degeneration from eval/longlamp_length_check.py, ROUGE from the
result JSON eval_longlamp.py already writes. Selecting on dev ROUGE is
legitimate precisely because it is dev.

The >600w threshold is calibrated against the no-adapter arm (0 false
positives, stable 400-600w) -- do not re-derive it and do not substitute a
gold-relative ratio.

GRID
----
Three families, because they fail differently:
  * no_repeat_ngram_size -- hard-blocks a repeated n-gram. Directly targets
    verbatim loops. Small n risks blocking legitimate repetition in long prose,
    so the grid spans 3/4/6 rather than committing to one.
  * sampling -- breaks the determinism that lets greedy fall into a cycle at
    all. Deterministic for a fixed seed, which is already applied to torch RNG.
  * a combination with a mild repetition_penalty, since LL1's single untuned
    1.3 was far too strong (it drove the baseline arm to 0.073) but 1.1 was
    never tried.

Each task also gets a greedy control at the same --limit, so the sweep carries
its own dev reference point rather than being compared against test numbers.

Usage:
    python condor/gen_longlamp_decoding_sweep_subs.py
    condor_submit condor/longlamp_decoding_sweep.sub
    python eval/longlamp_length_check.py results/LongLaMP_*_dev_*_limit50.predictions.jsonl
"""

from pathlib import Path

PROJECT_ROOT = Path("/home/ange00008/projects/mobileFT_distill")
CKPT = PROJECT_ROOT / "train" / "checkpoints"

# How many dev records per cell. Long-form generation at a 1024-token cap is
# the cost driver; 50 is enough to separate an 83%-degenerate arm from a
# near-zero one, which is all the stopping rule asks of it.
LIMIT = 50

TASKS = {
    "product_review_temporal": CKPT / "longlamp_lora_review_1ep_seed0" / "final",
    "abstract_generation_temporal": CKPT / "longlamp_lora_abstract_1ep_seed0" / "final",
    "topic_writing_temporal": CKPT / "longlamp_lora_topic_1ep_seed0" / "final",
}

# (cell label, decoding args). The label is documentation only -- the result
# filename is derived by eval_longlamp.py from the decoding values themselves,
# so a cell cannot land on a path that misdescribes what it ran.
# "greedy" passes an explicit no-op rather than an empty string: an empty value
# in a Condor `queue ... from` row is a parsing hazard, and --repetition-penalty
# 1.0 is both the default and untagged in the filename.
CELLS = [
    ("greedy_control", "--repetition-penalty 1.0"),
    ("nrng3", "--no-repeat-ngram-size 3"),
    ("nrng4", "--no-repeat-ngram-size 4"),
    ("nrng6", "--no-repeat-ngram-size 6"),
    ("sample_p90_t70", "--do-sample --top-p 0.9 --temperature 0.7"),
    ("sample_p95_t100", "--do-sample --top-p 0.95 --temperature 1.0"),
    ("nrng4_rp110", "--no-repeat-ngram-size 4 --repetition-penalty 1.1"),
]

HEADER_TMPL = '''# LongLaMP decoding sweep -- GENERATED by condor/gen_longlamp_decoding_sweep_subs.py
# Edit the generator, not this file.
#
# Branch A step 1: find a decoding config that stops the Task-LoRA repetition
# loop, chosen on the DEV split and then applied identically to every arm when
# LL1-LL6 are re-measured. No retraining -- every adapter is already on disk.
#
# Cells: {n_jobs} jobs, --limit {limit} each.
# Outputs carry a _limit{limit} suffix plus a decoding tag, so a sweep cell can
# never collide with a real result file.
#
# Read the results with:
#   python eval/longlamp_length_check.py results/LongLaMP_*_dev_*_limit{limit}.predictions.jsonl
# Admissible = degeneration rate at >600w near zero. Among admissible, pick
# best dev ROUGE-1 from the result JSONs. Never select on test.

universe              = docker
docker_image          = ghcr.io/gordofreemo/smollm3-train:ver4
executable            = eval/eval_longlamp.py

arguments             = --task $(task) --split dev --k 4 --seed 0 --limit {limit} --adapter $(adapter) $(decode_args)

output                = {root}/runlogs/longlamp_decsweep{sfx}.$(task).$(cell).$(ClusterId).$(ProcId).out
error                 = {root}/runlogs/longlamp_decsweep{sfx}.$(task).$(cell).$(ClusterId).$(ProcId).err
log                   = {root}/runlogs/longlamp_decsweep{sfx}.$(ClusterId).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
stream_output           = true
stream_error            = true
environment             = "MODEL_OUT_DIR={root}/data/models/SmolLM3-3B LONGLAMP_DIR={root}/data/longlamp CONDOR_CLUSTER_ID=$(ClusterId) CONDOR_PROC_ID=$(ProcId)"

gpus_minimum_memory     = 32000
gpus_minimum_capability = 8.0
# Blackwell (sm_120) guard -- ver4's torch 2.5.1+cu124 cannot target it.
require_gpus            = Capability >= 8.0 && Capability < 10.0
max_job_retirement_time = 600

request_GPUs          = 1
request_CPUs          = 2
request_memory        = 16G
# tyr1 (CUDA-busy oversubscription) and modi (uncorrectable ECC) cost R8 83/100
# jobs on its first big submit. Baked in from the first submit, per the
# convention gen_warm_subs.py / gen_r9_subs.py established.
requirements          = UidDomain == "cs.uni-saarland.de" && Machine != "tyr1.hpc.uni-saarland.de" && Machine != "modi.hpc.uni-saarland.de"
+WantGPUHomeMounted   = true
+WantScratchMounted   = true

queue task,adapter,cell,decode_args from (
'''


def emit(out_name: str, tasks: dict, cells: list, limit: int, sfx: str = "") -> int:
    rows = [f"  {task}, {adapter}, {cell}, {decode_args}"
            for task, adapter in tasks.items()
            for cell, decode_args in cells]
    header = HEADER_TMPL.format(
        root=PROJECT_ROOT, limit=limit, sfx=sfx, n_jobs=len(rows))
    out = PROJECT_ROOT / "condor" / out_name
    out.write_text(header + "\n".join(rows) + "\n)\n")
    print(f"[write] {out}  ({len(rows)} jobs, --limit {limit})")
    return len(rows)


def main():
    for task, adapter in TASKS.items():
        if not adapter.exists():
            raise SystemExit(f"ERROR: adapter missing: {adapter}")
        split_file = PROJECT_ROOT / "data" / "longlamp" / task / "val.json"
        if not split_file.exists():
            raise SystemExit(f"ERROR: dev split missing: {split_file}")

    # Smoke FIRST. All 21 cells share the same brand-new code path
    # (eval_longlamp.py's --no-repeat-ngram-size / --do-sample flags, added
    # 2026-08-04); a bug found after batching wastes the whole submit. Abstract
    # is the smoke task because its generations are shortest. Two cells, one
    # per new code path, so neither ships unexercised.
    smoke_tasks = {"abstract_generation_temporal": TASKS["abstract_generation_temporal"]}
    smoke_cells = [c for c in CELLS if c[0] in ("nrng4", "sample_p90_t70")]
    emit("longlamp_decoding_sweep_smoke.sub", smoke_tasks, smoke_cells, 3, "_smoke")

    emit("longlamp_decoding_sweep.sub", TASKS, CELLS, LIMIT)


if __name__ == "__main__":
    main()
