#!/usr/bin/env python3
"""Emit the Condor sub files for the OPPU faithful-replication round.

EDIT THIS SCRIPT, NOT THE .sub FILES (same convention as gen_newtask_subs.py,
gen_warm_subs.py, gen_r9_subs.py).

Generated:
    condor/oppu_rep_smoke.sub        7 jobs  (both stages, 1 test user, per task)
    condor/oppu_rep_task_lora.sub    7 jobs  (full task-LoRA training + RAG-arm eval)
    condor/oppu_rep_user.sub       ~65 jobs  (per-user OPPU stage, sharded 10 users/job)

Guards baked into every sub (project standard as of 2026-08-10):
  - tyr1/tyr2/modi excluded (CUDA-busy oversubscription ×2, uncorrectable ECC)
  - require_gpus Capability [8.0, 10.0) — Blackwell sm_120 has no ver4 kernels
  - PROJECT_ROOT + Condor ids in environment

The user stage needs the task-LoRA checkpoints on disk first: submit
oppu_rep_task_lora.sub, verify, then submit oppu_rep_user.sub.
`condor_submit` stays user-run for the batch subs.
"""

from pathlib import Path

ROOT = "/home/ange00008/projects/mobileFT_distill"
IMAGE = "ghcr.io/gordofreemo/smollm3-train:ver4"

# their task order; (task, n_test_users) — 2N has only 49 users in the release
TASKS = [
    ("citation", 100),
    ("movie_tagging", 100),
    ("news_categorize", 49),
    ("news_headline", 100),
    ("product_rating", 101),
    ("scholarly_title", 101),
    ("tweet_paraphrase", 100),
]
USERS_PER_SHARD = 10

GPU_REQS = ('requirements          = UidDomain == "cs.uni-saarland.de" && '
            'Machine != "tyr1.hpc.uni-saarland.de" && '
            'Machine != "tyr2.hpc.uni-saarland.de" && '
            'Machine != "modi.hpc.uni-saarland.de"')
def header(tag, executable, arguments, memory="32G"):
    return f"""universe              = docker
docker_image          = {IMAGE}
executable            = {executable}
arguments             = {arguments}

output                = {ROOT}/runlogs/{tag}.$(ClusterId).$(ProcId).out
error                 = {ROOT}/runlogs/{tag}.$(ClusterId).$(ProcId).err
log                   = {ROOT}/runlogs/{tag}.$(ClusterId).log

should_transfer_files = YES
stream_output           = true
stream_error            = true
when_to_transfer_output = ON_EXIT_OR_EVICT
environment           = "PROJECT_ROOT={ROOT} CONDOR_CLUSTER_ID=$(ClusterId) CONDOR_PROC_ID=$(ProcId)"

request_GPUs          = 1
request_CPUs          = 4
request_memory        = {memory}
{GPU_REQS}
+WantGPUHomeMounted   = true
gpus_minimum_memory     = 40000
gpus_minimum_capability = 8.0
require_gpus            = Capability >= 8.0 && Capability < 10.0
max_job_retirement_time = 28800
"""


def smoke_sub():
    s = ("# OPPU-replication smoke: both stages, 1 test user, all 7 tasks.\n"
         "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
         + header("oppu_rep_smoke_$(task)", f"{ROOT}/oppu_replication/smoke.sh", "$(task)",
                  memory="48G")  # product_rating's 2.8 GB user_others.json is json.load'd in-job
         + "\nqueue task from (\n"
         + "".join(f"    {t}\n" for t, _ in TASKS)
         + ")\n")
    return s


def task_lora_sub():
    s = ("# OPPU-replication stage 1: task-LoRA training (their recipe, k=1) +\n"
         "# RAG-arm eval over all test users. One job per task.\n"
         "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
         + header("oppu_rep_task_$(task)",
                  f"{ROOT}/oppu_replication/run_task_lora.py",
                  "--task_name $(task) --k 1",
                  memory="48G")  # product_rating's 2.8 GB user_others.json is json.load'd in-job
         + "\nqueue task from (\n"
         + "".join(f"    {t}\n" for t, _ in TASKS)
         + ")\n")
    return s


def user_sub():
    rows = []
    for t, n in TASKS:
        for start in range(0, n, USERS_PER_SHARD):
            end = min(start + USERS_PER_SHARD, n)
            rows.append(f"    {t} {start} {end}\n")
    s = ("# OPPU-replication stage 2: per-user LoRA + OPPU+RAG-arm eval, sharded\n"
         f"# {USERS_PER_SHARD} users/job. Needs stage-1 checkpoints on disk.\n"
         "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
         + header("oppu_rep_user_$(task)_$(ustart)",
                  f"{ROOT}/oppu_replication/run_oppu.py",
                  ("--task_name $(task) --k 1 "
                   f"--task_lora {ROOT}/train/checkpoints/oppu_rep/$(task)/task_lora_k1 "
                   "--user-start $(ustart) --user-end $(uend)"))
         + "\nqueue task, ustart, uend from (\n"
         + "".join(rows)
         + ")\n")
    return s


def base_sub():
    s = ("# OPPU-replication base arm: bare SmolLM3 + their k=1 retrieval prompts,\n"
         "# eval-only (no training). One job per task. Chart/writeup baseline.\n"
         "# Generated by condor/gen_oppu_subs.py — edit the generator.\n\n"
         + header("oppu_rep_base_$(task)",
                  f"{ROOT}/oppu_replication/run_task_lora.py",
                  "--task_name $(task) --k 1 --base-only")
         + "\nqueue task from (\n"
         + "".join(f"    {t}\n" for t, _ in TASKS)
         + ")\n")
    return s


def main():
    out = {
        "condor/oppu_rep_base.sub": base_sub(),
        "condor/oppu_rep_smoke.sub": smoke_sub(),
        "condor/oppu_rep_task_lora.sub": task_lora_sub(),
        "condor/oppu_rep_user.sub": user_sub(),
    }
    for path, content in out.items():
        p = Path(ROOT) / path
        p.write_text(content)
        print(f"wrote {path}")
    n_user_jobs = sum(-(-n // USERS_PER_SHARD) for _, n in TASKS)
    print(f"smoke: {len(TASKS)} jobs | task_lora: {len(TASKS)} jobs | user: {n_user_jobs} jobs")


if __name__ == "__main__":
    main()
