#!/usr/bin/env python3
"""
Emit the LL1-LL3 re-measurement sub (Branch A, step 2).

WHY
---
LL1 and LL3 reported that Task-LoRA fine-tuning REGRESSES badly on LongLaMP:

    task      floor    BM25 baseline   Task-LoRA    delta
    review    0.3282      0.3428         0.1818     -0.161
    topic     0.2824      0.2808         0.1311     -0.150
    abstract  0.3973      0.4306         0.4131     -0.017

The 2026-08-04 degeneration audit showed those Task-LoRA arms generate 817 and
802 median words against gold medians of 211 and 208, with 83/100 records past
600 words, while the same base model with no adapter never exceeds 358. The
regression and the repetition loop are perfectly confounded.

The 2026-08-04 dev decoding sweep (cluster 179265, 21 cells) then showed the
loop is fixable without retraining. Under --no-repeat-ngram-size 3 the dev
degeneration rate falls from 90%/88%/28% to 6%/4%/0% and dev ROUGE-1 on the
Task-LoRA arm rises to 0.3788 / 0.3055 / 0.4166.

WHAT THIS DOES NOT ASSUME
-------------------------
That the sweep numbers alone overturn LL1/LL3. They do not. The floor and BM25
baseline arms also generate long (topic floor 490 tok, baseline 579 tok), so
they may improve under the same config too. A Task-LoRA number measured with
the fix compared against a baseline measured without it would be exactly the
apples-to-oranges error that produced the retracted LL5 result in the first
place.

So all THREE arms are re-measured under the identical decoding config, on the
full test split, and the delta is read only from the re-measured table.

CONFIG: --no-repeat-ngram-size 3, selected on dev by the pre-registered rule
(admissible = >600w rate near zero; among admissible, best dev ROUGE-1). It was
tied-best on degeneration (6% worst-task) and best on mean dev ROUGE-1 (0.3670
across the three tasks). It also keeps decoding DETERMINISTIC, matching every
other round in this project; the runner-up (sampling at top_p=0.95) scored
0.3628 and would have introduced seed dependence.

Known limitation to carry into the writeup: n=3 forbids any trigram from
repeating within a generation, which can block legitimate repeated phrasing in
long prose. It won on dev ROUGE anyway, but it is a decoding intervention, not
a neutral fix, and the re-measured numbers should be described as such.

NOTE ON SPLIT VARIANT: LL1-LL3 ran on the `_user` task variant (that is what
their result files on disk use); the sweep ran on `_temporal`, which is where
LL4-LL6's adapters and pools live. Same adapters, same base model, different
partition -- so the config is selected on temporal dev and applied to user
test, and no dev record leaks into the test measurement either way.

Usage:
    python condor/gen_longlamp_remeasure_subs.py
    condor_submit condor/longlamp_remeasure_nrng3.sub
"""

from pathlib import Path

PROJECT_ROOT = Path("/home/ange00008/projects/mobileFT_distill")
CKPT = PROJECT_ROOT / "train" / "checkpoints"

# Selected on dev. Changing this means re-running the sweep, not editing here.
DECODE_ARGS = "--no-repeat-ngram-size 3"
DECODE_LABEL = "nrng3"

TASKS = {
    "product_review_user": CKPT / "longlamp_lora_review_1ep_seed0" / "final",
    "abstract_generation_user": CKPT / "longlamp_lora_abstract_1ep_seed0" / "final",
    "topic_writing_user": CKPT / "longlamp_lora_topic_1ep_seed0" / "final",
}

# (arm label, adapter, profile args). All three arms, identical decoding.
# The floor arm carries --no-profile; the other two retrieve BM25 k=4.
ARMS = [
    ("floor", "none", "--no-profile"),
    ("baseline", "none", "--k 4"),
    ("tasklora", "ADAPTER", "--k 4"),
]

HEADER = f'''# LongLaMP LL1-LL3 re-measurement under fixed decoding -- GENERATED by
# condor/gen_longlamp_remeasure_subs.py. Edit the generator, not this file.
#
# Branch A step 2. All three arms (floor / BM25 baseline / Task-LoRA) x three
# tasks, full test split, identical decoding: {DECODE_ARGS}.
# No retraining -- every adapter is already on disk.
#
# The point of re-running the floor and baseline arms, which did NOT visibly
# degenerate, is that a Task-LoRA number measured with the fix against a
# baseline measured without it is not a comparison. Read the delta only from
# the re-measured table.
#
# Results land at ..._seed0_{DECODE_LABEL}.json, alongside (not over) the
# existing plain-greedy files -- refuse-to-overwrite stays intact and the
# original LL1-LL3 numbers remain on disk for the before/after table.
#
# After it finishes:
#   python eval/longlamp_length_check.py results/LongLaMP_*_test_*_{DECODE_LABEL}.predictions.jsonl

universe              = docker
docker_image          = ghcr.io/gordofreemo/smollm3-train:ver4
executable            = eval/eval_longlamp.py

arguments             = --task $(task) --split test --seed 0 --resume --adapter $(adapter) $(profile_args) {DECODE_ARGS}

output                = {PROJECT_ROOT}/runlogs/longlamp_remeasure.$(task).$(arm).$(ClusterId).$(ProcId).out
error                 = {PROJECT_ROOT}/runlogs/longlamp_remeasure.$(task).$(arm).$(ClusterId).$(ProcId).err
log                   = {PROJECT_ROOT}/runlogs/longlamp_remeasure.$(ClusterId).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
stream_output           = true
stream_error            = true
environment             = "MODEL_OUT_DIR={PROJECT_ROOT}/data/models/SmolLM3-3B LONGLAMP_DIR={PROJECT_ROOT}/data/longlamp CONDOR_CLUSTER_ID=$(ClusterId) CONDOR_PROC_ID=$(ProcId)"

gpus_minimum_memory     = 32000
gpus_minimum_capability = 8.0
# Blackwell (sm_120) guard -- ver4's torch 2.5.1+cu124 cannot target it.
require_gpus            = Capability >= 8.0 && Capability < 10.0
# Full test splits (1822 / 4560 / 2452 records). --resume is on, so a preempted
# job continues from its own predictions file rather than restarting.
max_job_retirement_time = 600

request_GPUs          = 1
request_CPUs          = 2
request_memory        = 16G
requirements          = UidDomain == "cs.uni-saarland.de" && Machine != "tyr1.hpc.uni-saarland.de" && Machine != "modi.hpc.uni-saarland.de"
+WantGPUHomeMounted   = true
+WantScratchMounted   = true

queue task,adapter,arm,profile_args from (
'''


def main():
    rows = []
    for task, adapter in TASKS.items():
        if not adapter.exists():
            raise SystemExit(f"ERROR: adapter missing: {adapter}")
        if not (PROJECT_ROOT / "data" / "longlamp" / task / "test.json").exists():
            raise SystemExit(f"ERROR: test split missing for {task}")
        for arm, adapter_spec, profile_args in ARMS:
            resolved = str(adapter) if adapter_spec == "ADAPTER" else adapter_spec
            rows.append(f"  {task}, {resolved}, {arm}, {profile_args}")

    out = PROJECT_ROOT / "condor" / f"longlamp_remeasure_{DECODE_LABEL}.sub"
    out.write_text(HEADER + "\n".join(rows) + "\n)\n")
    print(f"[write] {out}  ({len(rows)} jobs = "
          f"{len(ARMS)} arms x {len(TASKS)} tasks, full test split, {DECODE_ARGS})")


if __name__ == "__main__":
    main()
