universe = docker
docker_image = ghcr.io/gordofreemo/smollm3-train:ver2
executable = condor/smoke_test.py
output = /home/ange00008/projects/mobileFT_distill/runlogs/smoke_test.$(ClusterId).$(ProcId).out
error = /home/ange00008/projects/mobileFT_distill/runlogs/smoke_test.$(ClusterId).$(ProcId).err
log = /home/ange00008/projects/mobileFT_distill/runlogs/smoke_test.$(ClusterId).log
should_transfer_files = YES
request_GPUs = 1 
request_CPUs = 2
request_memory = 8G 
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
+WantScratchMounted = true
queue 1

